apiVersion: v1
kind: Pod
metadata: 
  name: my-basic-pod
  namespace : example
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: nginx
    ports:
      - containerPort: 80