apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: service1deployment
  name: service1deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: sophiec0s/service1
        
