apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: service3deployment
  name: service3deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service3
  template:
    metadata:
      labels:
        app: service3
    spec:
      containers:
      - name: service3
        image: sophiec0s/service3
        ports:
        - containerPort: 5002