apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: service2deployment
  name: service2deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service2
  template:
    metadata:
      labels:
        app: service2
    spec:
      containers:
      - name: service2
        image: sophiec0s/service2
        ports:
        - containerPort: 5001