apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: nginxdeployment
  name: nginxdeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: sophiec0s/nginx
        ports:
        - containerPort: 80