apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: service4deployment
  name: service4deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service4
  template:
    metadata:
      labels:
        app: service4
    spec:
      containers:
      - name: service4
        image: sophiec0s/service4
        ports:
        - containerPort: 5003